// web/app/pages/categories.vue
<!--
  分类页 /categories

  展示分类树，层级缩进，点击跳转对应分类的文章列表。
-->
<template>
  <div class="max-w-3xl mx-auto px-6 py-16">
    <!-- 页面标题 -->
    <FadeIn direction="up" :delay="0">
      <div class="text-center mb-12">
        <h1 class="text-3xl font-serif-jp font-semibold text-heading tracking-widest">
          分类
        </h1>
        <p class="mt-3 text-sm text-placeholder tracking-wide">
          共 {{ categoryStore.categories.length }} 个分类
        </p>
      </div>
    </FadeIn>

    <!-- 加载中 -->
    <div v-if="categoryStore.loading && !categoryStore.categories.length" class="flex justify-center py-20">
      <WasLoading />
    </div>

    <!-- 分类树 -->
    <FadeIn v-else-if="categoryStore.categories.length" direction="up" :delay="100">
      <div class="space-y-1">
        <NuxtLink
          v-for="item in categoryStore.flatCategories"
          :key="item.category.id"
          :to="`/articles?category=${item.category.id}`"
          class="group flex items-center justify-between py-3 px-4
                 border-b border-subtle last:border-0
                 hover:bg-surface-hover transition-colors duration-200"
        >
          <div class="flex items-center gap-3">
            <!-- 层级缩进 -->
            <span class="inline-block" :style="{ width: `${item.depth * 1.5}rem` }" />
            <!-- 层级指示器 -->
            <span
              v-if="item.depth > 0"
              class="text-placeholder text-xs"
            >
              └
            </span>
            <span class="text-body group-hover:text-accent transition-colors duration-300">
              {{ item.category.name }}
            </span>
            <span
              v-if="item.category.description"
              class="text-xs text-placeholder hidden sm:inline"
            >
              {{ item.category.description }}
            </span>
          </div>
          <span class="text-xs text-placeholder">
            {{ item.category.articleCount }} 篇
          </span>
        </NuxtLink>
      </div>
    </FadeIn>

    <!-- 空状态 -->
    <WasEmpty v-else description="暂无分类" />
  </div>
</template>

<script setup lang="ts">
const categoryStore = useCategoryStore()

// 页面标题
useHead({
  title: '分类',
})

// 即时请求：静态部署下 payload 可能是旧数据
onMounted(() => {
  categoryStore.fetchCategories()
})
</script>

// ley-web/src/pages/categories.tsx
import { Link } from "react-router-dom";
import { FolderOpen } from "lucide-react";
import { useCategories, type Category } from "@/hooks/use-categories";
import { Empty } from "@/components/ui/Empty";
import { Skeleton } from "@/components/ui/Skeleton";

function CategoryNode({ category, depth }: { category: Category; depth: number }) {
  return (
    <li>
      <Link
        to={`/articles?category=${category.id}`}
        className="flex items-center justify-between rounded-xl px-3 py-2.5 text-sm transition-colors hover:bg-[var(--bg-hover)]"
        style={{ marginLeft: depth > 0 ? `${depth * 1.25}rem` : undefined }}
      >
        <span className="inline-flex min-w-0 items-center gap-2 text-[var(--text-primary)]">
          <FolderOpen className="size-4 shrink-0 text-[var(--accent)]" />
          <span className="truncate">{category.name}</span>
        </span>
        <span className="ml-3 shrink-0 rounded-lg bg-[var(--bg-hover)] px-2 py-0.5 text-xs text-[var(--text-tertiary)]">
          {category.article_count} 篇
        </span>
      </Link>
      {category.children.length > 0 && (
        <ul className="mt-0.5 space-y-0.5">
          {category.children.map((child) => (
            <CategoryNode key={child.id} category={child} depth={depth + 1} />
          ))}
        </ul>
      )}
    </li>
  );
}

/** 分类页：树形展示全部分类 */
export default function CategoriesPage() {
  const { data, isLoading } = useCategories();

  return (
    <div className="mx-auto max-w-4xl px-6 py-10">
      <h1 className="mb-2 text-2xl font-bold text-[var(--text-primary)]">分类</h1>
      <p className="mb-8 text-sm text-[var(--text-secondary)]">按主题归档文章</p>

      {isLoading ? (
        <div className="space-y-2">
          <Skeleton className="h-11" />
          <Skeleton className="h-11" />
          <Skeleton className="h-11" />
        </div>
      ) : !data || data.categories.length === 0 ? (
        <Empty title="暂无分类" />
      ) : (
        <ul className="card divide-y divide-[var(--border-light)] p-2">
          {data.categories.map((c) => (
            <CategoryNode key={c.id} category={c} depth={0} />
          ))}
        </ul>
      )}
    </div>
  );
}
